### ISSUE TITLE
image-capture-example - missing permission 

### ISSUE THREAD

**Issue by Sidchou** [ITPNYU/hacking-the-browser#1]
**image-capture-example** 
missing "activetab" permission
[link](https://github.com/ITPNYU/hacking-the-browser/blob/master/image-capture-example/manifest.json)

<img width="683" alt="Screen Shot 2019-03-25 at 3 44 19 AM" src="https://user-images.githubusercontent.com/29413975/54902793-aa4e9c80-4eb0-11e9-9985-c0a5e84ff2ec.png">

**Comment by bantic** [comment]
closed by #2
